baseURL       = "http://bad-ref.invalid"
languageCode  = "en-us"
title         = "Giuseppe Masino"

canonifyURLs  = false
relativeURLs  = true

enableGitInfo = true
enableInlineShortcodes = true
destination = "/mnt/projectRoot/build/hugo"

[params]
gitRepo = "https://github.com/qub1750ul/qub1750ul.me/"

[permalinks]
#	"blog" = "/:section/:year/:month/:title/"

[security.exec]
allow = ["^asciidoctor$"]
