baseURL       = "http://bad-ref.invalid"
languageCode  = "en-us"
title         = "qub1750ul's website"

canonifyURLs  = false
relativeURLs  = true

enableGitInfo = true
enableInlineShortcodes = true
destination = "/mnt/projectRoot/build/hugo"

[permalinks]
  "blog" = "/permalinks/v1/:section/:year/:month/:title/"

[security.exec]
  allow = ["^asciidoctor$"]