name: personal-website
region: fra

static_sites:

- name: personal-website
  routes:
  - path: /

  dockerfile_path: .do/dockerfile
  output_dir: build/hugo

  github:
    repo: qub1750ul/qub1750ul.me
    branch: main
    deploy_on_push: true
