+++
title = "Favourite blogs"
+++
:toc:

== Specer Baugh's blog
https://catern.com

A simple, old school, web 1.0 blog with a good amount of very interesting posts
(micro-essays ?) about pratical computing philosophy, including programming and
system administration.

== Julia Evans' blog
https://jvns.ca

About: https://jvns.ca/about/

This blog is about
* being delighted about programming
* showing how topics traditionally considered “hard” and “scary” are actually
  accessible and interesting and fun (TCP! / Kernel hacking! / Traceroute! /
	gzip! / databases! / SSL!)
* asking questions and getting better every day.
* how being clear & curious & humble is better than sounding like I know it all
  already
* experimenting with alternative ways to teach hard concepts (zines!)

== Matt Might's blog
http://matt.might.net

Dr. Matthew Might has been A CS and Internal Medicine professor at the
University of Alabama at Birmingham.
The articles on his blog cover various topics:
life hacking, computing and programming languages theory and tips, academic
life tips.

== The Overflow
https://stackoverflow.blog

A blog from people at StackOverflow.

== beepb00p's Website
https://beepb00p.xyz/exobrain/

A very interesting content packed blog and exobrain.

== Chuan Ji
https://jichu4n.com

A personal blog of a San Francisco engineer with a small but nice collection
of articles.

== public voit - Home page of Karl Voit
https://karl-voit.at

== ∑ Xah Code
http://xahlee.info

A blog of the "ugly but damn interesting" type

== David Gasquez's Handbook
https://publish.obsidian.md/davidgasquez

A very curated, long-form, exobrain.

== My friends' websites

=== Alberto Ventafridda
https://halb.it

[quote]
--
Hi, I'm Alberto.

I'm a computer science student at UniMib, living in Milan, Italy.
I like to work on projects that span the topics of cyber security, web
development, and distributed systems, occasionally writing about the
challenges I encounter.
--

=== Damiano Verzulli
https://dvblog.soabit.com

[quote]
--
I really like to spend time:

* investigating networking news and problems (at least in LAN and small WAN
  environments; from Ethernet to IPv4, up to BGP);
* improving my skills in system administration, expecially GNU/Linux
  environments;
* getting my hands on top of current Web 2.0 development standards (I started
  enjoying AngularJS and Bootstrap one year ago, when I finally understood
  that Javascript is no more what I knew lots and lots of year ago…)
--

=== Marco Russo
https://mrusso99.com/

