== Sites i like

This page is a list of sites i like. +
Each entry is organized in the following format:

- Short title
- Main URL
- About page
- Themes ?
- Personal tought

=== Julia Evans' blog
https://jvns.ca

About: https://jvns.ca/about/

....
This blog is about
- being delighted about programming
- showing how topics traditionally considered “hard” and “scary” are actually accessible and
  interesting and fun (TCP! / Kernel hacking! / Traceroute! / gzip! / databases! / SSL!)
- asking questions and getting better every day.
- how being clear & curious & humble is better than sounding like I know it all already
- experimenting with alternative ways to teach hard concepts (zines!)
....

=== Matt Might's blog
http://matt.might.net

Dr. Matthew Might has been A CS and Internal Medicine professor
at the University of Alabama at Birmingham. +
The articles on his blog cover various topics:
life hacking, computing and programming languages theory and tips,
academic life tips.

=== The Overflow
https://stackoverflow.blog

A blog from people at StackOverflow. +

=== beepb00p's Website
https://beepb00p.xyz/exobrain/

A very interesting content packed blog and exobrain.
