== Graphite pencil's hardness grades explained
:translate:

Data from https://www.mondoffice.com/mondoffice-informa/guida-all-acquisto/come-scegliere-la-matita-giusta.html[this web page].

La durezza di una matita è data dal tipo di mina, la sua anima in grafite, che ne influenza lo spessore e il colore del tratto.
Una matita con mina più dura presenterà un tratto più chiaro e sottile, ma anche più difficile da cancellare, mentre una mina più tenera offrirà un tratto spesso e scuro, più facile da cancellare, ma si consumerà anche più in fretta.
Esistono 2 tipi di scale per misurare la durezza di una matita, la scala britannica che utilizza le lettere e quella statunitense che utilizza invece i numeri. Nella tabella qui sotto si possono trovare entrambe le scale con alcune indicazioni sugli utilizzi più idonei.

[header,cols="4*"]
|===
2+| Grado durezza .2+| Caratteristiche .2+| Utilizzo
  | Britannico       | Statunitense

| 9B |
.5+| Molto morbide, tratto nero
.5+| Lavori artistici quali schizzi e bozze

| 8B |
| 7B |
| 6B |
| 5B |

| 4B |
.4+| Abbastanza morbide, tratto nero
.4+| Adatte al disegno a mano libera

| 3B |
| 2B | #0
| B  | #1

| HB | #2
.2+| Durezza media, tratto scuro
.2+| Piuttosto versatili, adatte alla scrittura

| F  | #21/2
| H  | #3
.2+| Mina dura, tratto grigio
.2+| Indicate per il disegno tecnico

| 2H | #4
| 3H | .3+| Piuttosto dure, tratto chiaro .3+| Idonea per progettazioni tecniche o grafiche a livelli avanzati
| 4H |
| 5H |
| 6H | .4+| Molto dure e con tratto molto chiaro .4+| Utilizzate per lavori di litografia, cartografia e xilografia
| 7H
| 8H
| 9H
|===

La lettera H indica le mine più dure (hard) mentre la lettera B indica quelle più morbide (black, ad indicare il tratto più scuro). La lettera F (fine point) invece indica una via di mezzo, né troppo dura né troppo morbida, che, insieme alla HB, via di mezzo leggermente più morbida, è  quella più indicata per l’utilizzo nelle scuole.

